In [2]:
import pandas as pd
import os

In [3]:
DATA_DIR = "../dataset/raw"

In [4]:
files = {
    "movies": "movies.csv",
    "posters": "posters.csv",
    "genres": "genres.csv",
    "actors": "actors.csv",
    "crew": "crew.csv",
    "languages": "languages.csv",
    "countries": "countries.csv",
    "releases": "releases.csv",
    "studios": "studios.csv",
    "themes": "themes.csv",
}

dfs = {}

for name, file in files.items():
    path = os.path.join(DATA_DIR, file)
    dfs[name] = pd.read_csv(path)
    print(name, dfs[name].shape)

movies (941597, 7)
posters (941597, 2)
genres (1046849, 2)
actors (5798450, 3)
crew (4720183, 3)
languages (1038762, 3)
countries (693476, 2)
releases (1332782, 5)
studios (679283, 2)
themes (125641, 2)

In [6]:
for name, df in dfs.items():
    print("\n" + "="*40)
    print(name.upper())
    print(df.head(3))
    print(df.columns.tolist())
    print(df.isna().sum().sort_values(ascending=False).head(10))
    print("duplicates:", df.duplicated().sum())

========================================
MOVIES
        id                               name    date  \
0  1000001                             Barbie  2023.0
1  1000002                           Parasite  2019.0
2  1000003  Everything Everywhere All at Once  2022.0

                                            tagline  \
0                  She's everything. He's just Ken.
1                       Act like you own the place.
2  The universe is so much bigger than you realize.

                                         description  minute  rating
0  Barbie and Ken are having the time of their li...   114.0    3.86
1  All unemployed, Ki-taek's family takes peculia...   133.0    4.56
2  An aging Chinese immigrant is swept up in an i...   140.0    4.30
['id', 'name', 'date', 'tagline', 'description', 'minute', 'rating']
rating         850598
tagline        802210
minute         181570
description    160812
date            91913
name               10
id                  0
dtype: int64
duplicates: 0

========================================
POSTERS
        id                                               link
0  1000001  https://a.ltrbxd.com/resized/film-poster/2/7/7...
1  1000002  https://a.ltrbxd.com/resized/film-poster/4/2/6...
2  1000003  https://a.ltrbxd.com/resized/film-poster/4/7/4...
['id', 'link']
link    180712
id           0
dtype: int64
duplicates: 0

========================================
GENRES
        id      genre
0  1000001     Comedy
1  1000001  Adventure
2  1000002     Comedy
['id', 'genre']
id       0
genre    0
dtype: int64
duplicates: 0

========================================
ACTORS
        id             name    role
0  1000001    Margot Robbie  Barbie
1  1000001     Ryan Gosling     Ken
2  1000001  America Ferrera  Gloria
['id', 'name', 'role']
role    1361559
name          4
id            0
dtype: int64
duplicates: 946

========================================
CREW
        id      role           name
0  1000001  Director   Greta Gerwig
1  1000001  Producer   Tom Ackerley
2  1000001  Producer  Margot Robbie
['id', 'role', 'name']
name    1
id      0
role    0
dtype: int64
duplicates: 1282

========================================
LANGUAGES
        id              type language
0  1000001          Language  English
1  1000002  Primary language   Korean
2  1000002   Spoken language  English
['id', 'type', 'language']
id          0
type        0
language    0
dtype: int64
duplicates: 0

========================================
COUNTRIES
        id      country
0  1000001           UK
1  1000001          USA
2  1000002  South Korea
['id', 'country']
id         0
country    0
dtype: int64
duplicates: 0

========================================
RELEASES
        id    country        date        type rating
0  1000001    Andorra  2023-07-21  Theatrical    NaN
1  1000001  Argentina  2023-07-20  Theatrical    ATP
2  1000001  Australia  2023-07-19  Theatrical     PG
['id', 'country', 'date', 'type', 'rating']
rating     998802
id              0
country         0
date            0
type            0
dtype: int64
duplicates: 0

========================================
STUDIOS
        id                   studio
0  1000001  LuckyChap Entertainment
1  1000001             Heyday Films
2  1000001           NB/GG Pictures
['id', 'studio']
studio    10
id         0
dtype: int64
duplicates: 212

========================================
THEMES
        id                             theme
0  1000001  Humanity and the world around us
1  1000001            Crude humor and satire
2  1000001       Moving relationship stories
['id', 'theme']
id       0
theme    0
dtype: int64
duplicates: 0

In [7]:
movies = dfs["movies"]
movies.info()
movies.head()
movies.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941597 entries, 0 to 941596
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           941597 non-null  int64
 1   name         941587 non-null  object
 2   date         849684 non-null  float64
 3   tagline      139387 non-null  object
 4   description  780785 non-null  object
 5   minute       760027 non-null  float64
 6   rating       90999 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 50.3+ MB

,id,name,date,tagline,description,minute,rating
count,9.415970e+05,941587,849684.000000,139387,780785,760027.000000,90999.000000
unique,NaN,795421,NaN,135521,763348,NaN,NaN
top,NaN,Home,NaN,animation short,Mexican feature film,NaN,NaN
freq,NaN,143,NaN,100,893,NaN,NaN
mean,1.470799e+06,NaN,1998.522300,NaN,NaN,65.776516,3.244043
std,2.718158e+05,NaN,27.534865,NaN,NaN,154.828161,0.417281
min,1.000001e+06,NaN,1874.000000,NaN,NaN,1.000000,0.880000
25%,1.235400e+06,NaN,1986.000000,NaN,NaN,15.000000,3.020000
50%,1.470799e+06,NaN,2010.000000,NaN,NaN,62.000000,3.300000
75%,1.706198e+06,NaN,2019.000000,NaN,NaN,92.000000,3.510000
max,1.941597e+06,NaN,2031.000000,NaN,NaN,72000.000000,4.690000

In [8]:
movies.sample(10)

,id,name,date,tagline,description,minute,rating
766364,1766365,The Racial Politics of Abortion,2020.0,NaN,Acclaimed filmmaker Dawn Porter 's intimate an...,26.0,NaN
900629,1900630,德云社庚子年开箱庆典,2020.0,NaN,NaN,NaN,NaN
561307,1561308,Mike Portnoy - Drumavarium,2005.0,NaN,Mike’s drum-cam footage from Dream Theaters Oc...,66.0,NaN
816857,1816858,县委书记,1958.0,NaN,NaN,100.0,NaN
796785,1796786,Lumigo,NaN,NaN,Eleonora and Giusi have to realize an art proj...,5.0,NaN
485474,1485475,How to Get Low Income,2019.0,NaN,"One day, Jung-hyeok receives a sudden proposal...",11.0,NaN
149266,1149267,Banjo,2016.0,NaN,"A musical drama film directed by Ravi Jadhav, ...",140.0,NaN
776583,1776584,Romance and Brass Tacks,1918.0,NaN,Romance and Brass Tacks is a silent short.,NaN,NaN
377288,1377289,Kadam Kadha,2017.0,NaN,"Two friends, Cleatus & Giri work together to r...",121.0,NaN
70413,1070414,Long Day's Journey Into Night,NaN,NaN,"Over the course of a day, a married couple, Ma...",NaN,NaN

In [9]:
posters = dfs["posters"]
genres = dfs["genres"]

print(posters.shape)
print(posters.head())
print(genres.shape)
print(genres.head())

(941597, 2)
        id                                               link
0  1000001  https://a.ltrbxd.com/resized/film-poster/2/7/7...
1  1000002  https://a.ltrbxd.com/resized/film-poster/4/2/6...
2  1000003  https://a.ltrbxd.com/resized/film-poster/4/7/4...
3  1000004  https://a.ltrbxd.com/resized/film-poster/5/1/5...
4  1000005  https://a.ltrbxd.com/resized/film-poster/2/4/0...
(1046849, 2)
        id      genre
0  1000001     Comedy
1  1000001  Adventure
2  1000002     Comedy
3  1000002   Thriller
4  1000002      Drama

In [10]:
genres = dfs["genres"]
actors = dfs["actors"]

print("genres:", genres.shape)
print(genres.head())

print("actors:", actors.shape)
print(actors.head())

genres: (1046849, 2)
        id      genre
0  1000001     Comedy
1  1000001  Adventure
2  1000002     Comedy
3  1000002   Thriller
4  1000002      Drama
actors: (5798450, 3)
        id               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie

In [11]:
print(genres["id"].value_counts().head(10))
print(actors["id"].value_counts().head(10))

id
1452952    17
1346650    16
1549210    13
1676417    12
1676160    12
1648174    12
1548734    12
1237553    12
1508026    11
1410845    11
Name: count, dtype: int64
id
1123471    555
1027275    451
1138767    354
1018495    346
1000179    331
1001509    322
1007519    315
1000296    298
1495515    283
1170566    281
Name: count, dtype: int64

In [12]:
sample_id = 1000001

print(genres[genres["id"] == sample_id])
print(actors[actors["id"] == sample_id])

        id      genre
0  1000001     Comedy
1  1000001  Adventure
          id               name    role
0    1000001      Margot Robbie  Barbie
1    1000001       Ryan Gosling     Ken
2    1000001    America Ferrera  Gloria
3    1000001  Ariana Greenblatt   Sasha
4    1000001           Issa Rae  Barbie
..       ...                ...     ...
162  1000001          Josh Wild  Dancer
163  1000001   Joe Wolstenholme  Dancer
164  1000001  Richard Womersley  Dancer
165  1000001       Ashley Young  Dancer
166  1000001        Naomi Watts  Barbie

[167 rows x 3 columns]

In [13]:
print(posters.shape)
print(posters.head())

print(genres["id"].nunique(), "unique movies in genres")
print(actors["id"].nunique(), "unique movies in actors")

(941597, 2)
        id                                               link
0  1000001  https://a.ltrbxd.com/resized/film-poster/2/7/7...
1  1000002  https://a.ltrbxd.com/resized/film-poster/4/2/6...
2  1000003  https://a.ltrbxd.com/resized/film-poster/4/7/4...
3  1000004  https://a.ltrbxd.com/resized/film-poster/5/1/5...
4  1000005  https://a.ltrbxd.com/resized/film-poster/2/4/0...
676491 unique movies in genres
634302 unique movies in actors

In [14]:
actors = dfs["actors"]

sample_id = 1000001
sample_actors = actors[actors["id"] == sample_id]

print(sample_actors.head(10))
print("Total actors for this movie:", len(sample_actors))

        id               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie
5  1000001      Kate McKinnon  Barbie
6  1000001    Alexandra Shipp  Barbie
7  1000001        Emma Mackey  Barbie
8  1000001           Hari Nef  Barbie
9  1000001      Sharon Rooney  Barbie
Total actors for this movie: 167

In [15]:
actors_work = actors[["id", "name", "role"]].copy()

actors_work["name"] = actors_work["name"].fillna("")
actors_work["role"] = actors_work["role"].fillna("")

# Har movie ke liye sirf pehle 7 actors lo
actors_work["rank"] = actors_work.groupby("id").cumcount()

actors_top7 = actors_work[actors_work["rank"] < 7].copy()

actors_top7["cast_item"] = (
    actors_top7["name"].str.strip() + " as " + actors_top7["role"].str.strip()
)

actors_clean = (
    actors_top7.groupby("id", sort=False)["cast_item"]
    .agg(" | ".join)
    .reset_index(name="main_cast")
)

In [16]:
genres_clean = (
    genres.groupby("id")["genre"]
    .apply(lambda x: " | ".join(sorted(set(x))))
    .reset_index(name="genres")
)

In [17]:
posters_clean = posters.rename(columns={"link": "poster_url"})

In [18]:
movies_clean = movies.copy()

movies_clean = movies_clean[
    movies_clean["minute"].notna() & (movies_clean["minute"] >= 60)
].copy()

In [19]:
movies_clean["date"] = movies_clean["date"].astype("Int64")
movies_clean["minute"] = movies_clean["minute"].astype("Int64")
movies_clean["rating"] = movies_clean["rating"].astype("float")

In [20]:
movies_clean = movies_clean.rename(columns={
    "id": "movie_id",
    "name": "title",
    "date": "release_year",
    "minute": "runtime_minutes",
    "rating": "avg_rating",
    "description": "overview"
})

In [21]:
genres_clean = (
    genres.groupby("id", sort=False)["genre"]
    .agg(lambda x: " | ".join(pd.unique(x)))
    .reset_index(name="genres")
)

In [23]:
actors_clean.head(10)

        id                                          main_cast
0  1000001  Margot Robbie as Barbie | Ryan Gosling as Ken ...
1  1000002  Song Kang-ho as Kim Ki-taek | Lee Sun-kyun as ...
2  1000003  Michelle Yeoh as Evelyn Wang | Ke Huy Quan as ...
3  1000004  Edward Norton as Narrator | Brad Pitt as Tyler...
4  1000005  Ryan Gosling as Sebastian | Emma Stone as Mia ...
5  1000006  Cillian Murphy as J. Robert Oppenheimer | Emil...
6  1000007  Matthew McConaughey as Joseph 'Coop' Cooper | ...
7  1000008  Joaquin Phoenix as Arthur Fleck / Joker | Robe...
8  1000009  Timothée Chalamet as Paul Atreides | Rebecca F...
9  1000010  John Travolta as Vincent Vega | Samuel L. Jack...

In [24]:
final_movies = movies_clean.merge(genres_clean, left_on="movie_id", right_on="id", how="left")
final_movies = final_movies.merge(actors_clean, left_on="movie_id", right_on="id", how="left", suffixes=("", "_actors"))
final_movies = final_movies.merge(posters_clean, left_on="movie_id", right_on="id", how="left", suffixes=("", "_posters"))

In [27]:
final_movies.head(5)

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,id,genres,id_actors,main_cast,id_posters,poster_url
0,1000001,Barbie,2023,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114,3.86,1000001.0,Comedy | Adventure,1000001.0,Margot Robbie as Barbie | Ryan Gosling as Ken ...,1000001,https://a.ltrbxd.com/resized/film-poster/2/7/7...
1,1000002,Parasite,2019,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133,4.56,1000002.0,Comedy | Thriller | Drama,1000002.0,Song Kang-ho as Kim Ki-taek | Lee Sun-kyun as ...,1000002,https://a.ltrbxd.com/resized/film-poster/4/2/6...
2,1000003,Everything Everywhere All at Once,2022,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140,4.30,1000003.0,Science Fiction | Adventure | Comedy | Action,1000003.0,Michelle Yeoh as Evelyn Wang | Ke Huy Quan as ...,1000003,https://a.ltrbxd.com/resized/film-poster/4/7/4...
3,1000004,Fight Club,1999,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139,4.27,1000004.0,Drama,1000004.0,Edward Norton as Narrator | Brad Pitt as Tyler...,1000004,https://a.ltrbxd.com/resized/film-poster/5/1/5...
4,1000005,La La Land,2016,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129,4.09,1000005.0,Drama | Comedy | Music | Romance,1000005.0,Ryan Gosling as Sebastian | Emma Stone as Mia ...,1000005,https://a.ltrbxd.com/resized/film-poster/2/4/0...

In [28]:
movies_clean = movies.copy()
movies_clean = movies_clean[
    movies_clean["minute"].notna() & (movies_clean["minute"] >= 60)
].copy()

movies_clean.shape

(395953, 7)

In [29]:
genres_clean = (
    genres.groupby("id", sort=False)["genre"]
    .agg(lambda x: " | ".join(pd.unique(x)))
    .reset_index(name="genres")
)

genres_clean.head()

        id                                         genres
0  1000001                             Comedy | Adventure
1  1000002                      Comedy | Thriller | Drama
2  1000003  Science Fiction | Adventure | Comedy | Action
3  1000004                                          Drama
4  1000005               Drama | Comedy | Music | Romance

In [30]:
final_movies = final_movies.drop(columns=[col for col in final_movies.columns if col.startswith("id")])

final_movies.head()

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,genres,main_cast,poster_url
0,1000001,Barbie,2023,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114,3.86,Comedy | Adventure,Margot Robbie as Barbie | Ryan Gosling as Ken ...,https://a.ltrbxd.com/resized/film-poster/2/7/7...
1,1000002,Parasite,2019,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133,4.56,Comedy | Thriller | Drama,Song Kang-ho as Kim Ki-taek | Lee Sun-kyun as ...,https://a.ltrbxd.com/resized/film-poster/4/2/6...
2,1000003,Everything Everywhere All at Once,2022,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140,4.30,Science Fiction | Adventure | Comedy | Action,Michelle Yeoh as Evelyn Wang | Ke Huy Quan as ...,https://a.ltrbxd.com/resized/film-poster/4/7/4...
3,1000004,Fight Club,1999,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139,4.27,Drama,Edward Norton as Narrator | Brad Pitt as Tyler...,https://a.ltrbxd.com/resized/film-poster/5/1/5...
4,1000005,La La Land,2016,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129,4.09,Drama | Comedy | Music | Romance,Ryan Gosling as Sebastian | Emma Stone as Mia ...,https://a.ltrbxd.com/resized/film-poster/2/4/0...

In [31]:
print(final_movies.shape)
print(final_movies.columns.tolist())

(395953, 10)
['movie_id', 'title', 'release_year', 'tagline', 'overview', 'runtime_minutes', 'avg_rating', 'genres', 'main_cast', 'poster_url']

In [43]:
crew = dfs["crew"]

crew.head(100)

         id      role                   name
0   1000001  Director           Greta Gerwig
1   1000001  Producer           Tom Ackerley
2   1000001  Producer          Margot Robbie
3   1000001  Producer         Robbie Brenner
4   1000001  Producer           David Heyman
..      ...       ...                    ...
95  1000001    Stunts             Chris Reid
96  1000001    Stunts         Natalie Rivera
97  1000001    Stunts         Elliot Collins
98  1000001    Stunts        Jessica Barfoot
99  1000001    Stunts  Sebastian Zaniesienko

[100 rows x 3 columns]

In [36]:
crew.columns.tolist()

['id', 'role', 'name']

In [37]:
crew_work = crew.copy()

crew_work.columns = [col.lower() for col in crew_work.columns]

director_col = "job" if "job" in crew_work.columns else "role"

director_df = crew_work[
    crew_work[director_col].astype(str).str.lower().str.contains("director", na=False)
].copy()

director_clean = (
    director_df.groupby("id", sort=False)["name"]
    .agg(lambda x: " | ".join(pd.unique(x)))
    .reset_index(name="director")
)

director_clean.head()

        id                                           director
0  1000001  Greta Gerwig | David Keadell | Danni Lizaitis ...
1  1000002      Bong Joon-ho | Kim Seong-sik | Yoon Young-woo
2  1000003  Daniel Scheinert | Daniel Kwan | Rod Smith | J...
3  1000004        David Fincher | Bob Wagner | Mike Topoozian
4  1000005          Damien Chazelle | Paula Case | Peter Kohn

In [38]:
final_movies = final_movies.merge(
    director_clean,
    left_on="movie_id",
    right_on="id",
    how="left"
)

In [39]:
final_movies = final_movies.drop(columns=[col for col in final_movies.columns if col.startswith("id")])

final_movies.head()

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,genres,main_cast,poster_url,director
0,1000001,Barbie,2023,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114,3.86,Comedy | Adventure,Margot Robbie as Barbie | Ryan Gosling as Ken ...,https://a.ltrbxd.com/resized/film-poster/2/7/7...,Greta Gerwig | David Keadell | Danni Lizaitis ...
1,1000002,Parasite,2019,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133,4.56,Comedy | Thriller | Drama,Song Kang-ho as Kim Ki-taek | Lee Sun-kyun as ...,https://a.ltrbxd.com/resized/film-poster/4/2/6...,Bong Joon-ho | Kim Seong-sik | Yoon Young-woo
2,1000003,Everything Everywhere All at Once,2022,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140,4.30,Science Fiction | Adventure | Comedy | Action,Michelle Yeoh as Evelyn Wang | Ke Huy Quan as ...,https://a.ltrbxd.com/resized/film-poster/4/7/4...,Daniel Scheinert | Daniel Kwan | Rod Smith | J...
3,1000004,Fight Club,1999,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139,4.27,Drama,Edward Norton as Narrator | Brad Pitt as Tyler...,https://a.ltrbxd.com/resized/film-poster/5/1/5...,David Fincher | Bob Wagner | Mike Topoozian
4,1000005,La La Land,2016,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129,4.09,Drama | Comedy | Music | Romance,Ryan Gosling as Sebastian | Emma Stone as Mia ...,https://a.ltrbxd.com/resized/film-poster/2/4/0...,Damien Chazelle | Paula Case | Peter Kohn

In [45]:
crew["role"].unique()[:30]

array(['Director', 'Producer', 'Writer', 'Casting', 'Editor',
       'Cinematography', 'Assistant director', 'Additional directing',
       'Executive producer', 'Lighting', 'Camera operator',
       'Additional photography', 'Production design', 'Art direction',
       'Set decoration', 'Special effects', 'Visual effects', 'Stunts',
       'Choreography', 'Composer', 'Songs', 'Sound', 'Costume design',
       'Makeup', 'Hairstyling', 'Story', 'Original writer',
       'Title design', 'Co-director'], dtype=object)

In [46]:
crew.iloc[:,2].unique()[:30]

array(['Greta Gerwig', 'Tom Ackerley', 'Margot Robbie', 'Robbie Brenner',
       'David Heyman', 'Christine Crais', 'Noah Baumbach', 'Lucy Bevan',
       'Allison Jones', 'Olivia Grant', 'Emily Buntyn', 'Nick Houy',
       'Rodrigo Prieto', 'David Keadell', 'Danni Lizaitis',
       'Josh Robertson', 'Matthew R. Milan', 'Zoe Tough',
       'Sarah Townsend', 'George Cottle', 'John Sorapure',
       'Richard Dickson', 'Josey McNamara', 'Ynon Kreiz', 'Michael Sharp',
       'Courtenay Valenti', 'Toby Emmerich', 'Cate Adams', 'Manny Tapia',
       'Lee Walters'], dtype=object)

In [47]:
director_df = crew[crew["role"] == "Director"]

director_clean = (
    director_df.groupby("id", sort=False)["name"]
    .agg(lambda x: " | ".join(pd.unique(x)))
    .reset_index(name="director")
)

director_clean.head()

        id                        director
0  1000001                    Greta Gerwig
1  1000002                    Bong Joon-ho
2  1000003  Daniel Scheinert | Daniel Kwan
3  1000004                   David Fincher
4  1000005                 Damien Chazelle

In [48]:
producer_df = crew[crew["role"] == "Producer"].copy()

producer_df["rank"] = producer_df.groupby("id").cumcount()

producer_df = producer_df[producer_df["rank"] < 3]

producer_clean = (
    producer_df.groupby("id", sort=False)["name"]
    .agg(" | ".join)
    .reset_index(name="producer")
)

producer_clean.head()

        id                                        producer
0  1000001   Tom Ackerley | Margot Robbie | Robbie Brenner
1  1000002  Jang Young-hwan | Kwak Sin-ae | Moon Yang-kwon
2  1000003       Joe Russo | Anthony Russo | Jonathan Wang
3  1000004   Ross Grayson Bell | Ceán Chaffin | Art Linson
4  1000005      Jordan Horowitz | Fred Berger | Marc Platt

In [49]:
final_movies = final_movies.merge(
    director_clean,
    left_on="movie_id",
    right_on="id",
    how="left"
)

final_movies = final_movies.drop(columns=["id"])

final_movies = final_movies.merge(
    producer_clean,
    left_on="movie_id",
    right_on="id",
    how="left"
)

final_movies = final_movies.drop(columns=["id"])

final_movies.head()

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,genres,main_cast,poster_url,director_x,director_y,producer
0,1000001,Barbie,2023,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114,3.86,Comedy | Adventure,Margot Robbie as Barbie | Ryan Gosling as Ken ...,https://a.ltrbxd.com/resized/film-poster/2/7/7...,Greta Gerwig | David Keadell | Danni Lizaitis ...,Greta Gerwig,Tom Ackerley | Margot Robbie | Robbie Brenner
1,1000002,Parasite,2019,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133,4.56,Comedy | Thriller | Drama,Song Kang-ho as Kim Ki-taek | Lee Sun-kyun as ...,https://a.ltrbxd.com/resized/film-poster/4/2/6...,Bong Joon-ho | Kim Seong-sik | Yoon Young-woo,Bong Joon-ho,Jang Young-hwan | Kwak Sin-ae | Moon Yang-kwon
2,1000003,Everything Everywhere All at Once,2022,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140,4.30,Science Fiction | Adventure | Comedy | Action,Michelle Yeoh as Evelyn Wang | Ke Huy Quan as ...,https://a.ltrbxd.com/resized/film-poster/4/7/4...,Daniel Scheinert | Daniel Kwan | Rod Smith | J...,Daniel Scheinert | Daniel Kwan,Joe Russo | Anthony Russo | Jonathan Wang
3,1000004,Fight Club,1999,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139,4.27,Drama,Edward Norton as Narrator | Brad Pitt as Tyler...,https://a.ltrbxd.com/resized/film-poster/5/1/5...,David Fincher | Bob Wagner | Mike Topoozian,David Fincher,Ross Grayson Bell | Ceán Chaffin | Art Linson
4,1000005,La La Land,2016,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129,4.09,Drama | Comedy | Music | Romance,Ryan Gosling as Sebastian | Emma Stone as Mia ...,https://a.ltrbxd.com/resized/film-poster/2/4/0...,Damien Chazelle | Paula Case | Peter Kohn,Damien Chazelle,Jordan Horowitz | Fred Berger | Marc Platt

In [51]:
crew[crew["name"] == "David Keadell"]

             id                role           name
14      1000001  Assistant director  David Keadell
3676    1000041  Assistant director  David Keadell
20136   1000236  Assistant director  David Keadell
39784   1000510  Assistant director  David Keadell
70009   1000985  Assistant director  David Keadell
117003  1001859  Assistant director  David Keadell
124286  1002003  Assistant director  David Keadell

In [52]:
director_df = crew[
    crew["role"] == "Director"
]

In [53]:
final_movies = final_movies.drop(columns=["director_x"])

final_movies = final_movies.rename(
    columns={
        "director_y": "director"
    }
)

In [54]:
final_movies.columns.tolist()

['movie_id',
 'title',
 'release_year',
 'tagline',
 'overview',
 'runtime_minutes',
 'avg_rating',
 'genres',
 'main_cast',
 'poster_url',
 'director',
 'producer']

In [55]:
final_movies.head()

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,genres,main_cast,poster_url,director,producer
0,1000001,Barbie,2023,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114,3.86,Comedy | Adventure,Margot Robbie as Barbie | Ryan Gosling as Ken ...,https://a.ltrbxd.com/resized/film-poster/2/7/7...,Greta Gerwig,Tom Ackerley | Margot Robbie | Robbie Brenner
1,1000002,Parasite,2019,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133,4.56,Comedy | Thriller | Drama,Song Kang-ho as Kim Ki-taek | Lee Sun-kyun as ...,https://a.ltrbxd.com/resized/film-poster/4/2/6...,Bong Joon-ho,Jang Young-hwan | Kwak Sin-ae | Moon Yang-kwon
2,1000003,Everything Everywhere All at Once,2022,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140,4.30,Science Fiction | Adventure | Comedy | Action,Michelle Yeoh as Evelyn Wang | Ke Huy Quan as ...,https://a.ltrbxd.com/resized/film-poster/4/7/4...,Daniel Scheinert | Daniel Kwan,Joe Russo | Anthony Russo | Jonathan Wang
3,1000004,Fight Club,1999,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139,4.27,Drama,Edward Norton as Narrator | Brad Pitt as Tyler...,https://a.ltrbxd.com/resized/film-poster/5/1/5...,David Fincher,Ross Grayson Bell | Ceán Chaffin | Art Linson
4,1000005,La La Land,2016,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129,4.09,Drama | Comedy | Music | Romance,Ryan Gosling as Sebastian | Emma Stone as Mia ...,https://a.ltrbxd.com/resized/film-poster/2/4/0...,Damien Chazelle,Jordan Horowitz | Fred Berger | Marc Platt

In [57]:
print("Total Movies:", len(movies))

print("Runtime Missing:",
      movies["minute"].isna().sum())

print("Runtime < 60:",
      (movies["minute"] < 60).sum())

print("Runtime >= 60:",
      (movies["minute"] >= 60).sum())

print("Final:",
      len(movies[
          movies["minute"].notna() &
          (movies["minute"] >= 60)
      ]))

Total Movies: 941597
Runtime Missing: 181570
Runtime < 60: 364074
Runtime >= 60: 395953
Final: 395953

In [58]:
movies[movies["minute"].isna()][["id", "name", "date"]].head(20)

           id                                    name    date
2572  1002573                               Nosferatu  2024.0
3529  1003530     Spider-Man: Beyond the Spider-Verse     NaN
4679  1004680                    The Batman - Part II  2026.0
5493  1005494  Wake Up Dead Man: A Knives Out Mystery     NaN
5554  1005555                                  Wicked  2024.0
5768  1005769                 Beetlejuice Beetlejuice  2024.0
6491  1006492                            Gladiator II  2024.0
6666  1006667                          Alien: Romulus  2024.0
7119  1007120          My Year of Rest and Relaxation     NaN
7227  1007228                                   Blade  2025.0
7441  1007442                      The Fantastic Four  2025.0
7787  1007788                   Mission: Impossible 8  2025.0
7914  1007915                            Frankenstein     NaN
7945  1007946                                Avatar 3  2025.0
8110  1008111                  Mad Max: The Wasteland     NaN
8248  1008249                      Paddington in Peru  2024.0
8558  1008559        Captain America: Brave New World  2025.0
8603  1008604                       Sherlock Holmes 3     NaN
8706  1008707                        Dune: Part Three     NaN
8710  1008711                         We Live in Time  2024.0

In [59]:
movies_clean = movies.copy()

# Sirf runtime 60 min se kam wali movies remove karo
movies_clean = movies_clean[
    (movies_clean["minute"].isna()) |
    (movies_clean["minute"] >= 60)
].copy()

movies_clean = movies_clean.rename(columns={
    "id": "movie_id",
    "name": "title",
    "date": "release_year",
    "minute": "runtime_minutes",
    "rating": "avg_rating",
    "description": "overview"
})

movies_clean["release_year"] = movies_clean["release_year"].astype("Int64")
movies_clean["runtime_minutes"] = movies_clean["runtime_minutes"].astype("Int64")
movies_clean["avg_rating"] = movies_clean["avg_rating"].astype("float")

print(movies_clean.shape)
movies_clean.head()

(577523, 7)

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating
0,1000001,Barbie,2023,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114,3.86
1,1000002,Parasite,2019,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133,4.56
2,1000003,Everything Everywhere All at Once,2022,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140,4.30
3,1000004,Fight Club,1999,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139,4.27
4,1000005,La La Land,2016,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129,4.09

In [60]:
final_movies = movies_clean.merge(
    genres_clean,
    left_on="movie_id",
    right_on="id",
    how="left"
)

final_movies = final_movies.merge(
    actors_clean,
    left_on="movie_id",
    right_on="id",
    how="left",
    suffixes=("", "_actors")
)

final_movies = final_movies.merge(
    posters_clean,
    left_on="movie_id",
    right_on="id",
    how="left",
    suffixes=("", "_posters")
)

final_movies = final_movies.merge(
    director_clean,
    left_on="movie_id",
    right_on="id",
    how="left",
    suffixes=("", "_director")
)

final_movies = final_movies.merge(
    producer_clean,
    left_on="movie_id",
    right_on="id",
    how="left",
    suffixes=("", "_producer")
)

# Extra id columns remove
final_movies = final_movies.loc[:, ~final_movies.columns.str.startswith("id")]

print(final_movies.shape)

(577523, 12)

In [66]:
final_movies.sample(10)

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,genres,main_cast,poster_url,director,producer
240883,1347021,Losing Sleep,2020,NaN,"While our nights have never been shorter, an e...",85,NaN,Documentary,Anna Flori-Lamour as Narrator,https://a.ltrbxd.com/resized/film-poster/6/7/3...,Thierry Robert,NaN
354102,1549155,Motu Patlu the Superheroes – Super Villains fr...,2019,NaN,Friends Motu and Patlu must save the world fro...,79,NaN,Animation,NaN,https://a.ltrbxd.com/resized/film-poster/7/3/4...,Suhas Kadav,NaN
215174,1303248,Une famille pas comme les autres,2005,NaN,Pre-teen rascal Michel-Ange 'Mikey' is lovingl...,95,NaN,Romance | Drama,NaN,https://a.ltrbxd.com/resized/film-poster/5/3/5...,Édouard Molinaro,Anne Leduc | Jean-Luc Azoulay | Michel Boucau
108691,1136771,The Dirty War on the NHS,2019,The NHS is in crisis. John Pigler's latest fil...,John Pilger unearths the hidden agenda behind ...,120,NaN,Documentary,John Pilger as,https://a.ltrbxd.com/resized/film-poster/5/6/7...,John Pilger,NaN
45342,1051356,Believeland,2016,NaN,The Drive. The Fumble. The Shot. The Decision....,78,3.43,Documentary,NaN,https://a.ltrbxd.com/resized/film-poster/3/2/3...,Andrew Billman,Marquis Daisy | Gentry Kirby | Scott Raab
547217,1888873,Das unheimliche Tal,2012,NaN,NaN,<NA>,NaN,Drama,Anna Bardorf as Margit Schwarz | Inga Busch as...,NaN,NaN,NaN
159904,1212910,Brian Cox: Seven Days on Mars,2022,NaN,"With unique access to Nasa, Brian Cox follows ...",89,NaN,Documentary,Brian Cox as,https://a.ltrbxd.com/resized/film-poster/8/9/0...,Michael Lachmann,NaN
489211,1793420,Alice: A True Story,2014,NaN,Alice: A True Story is a psychological film sc...,<NA>,NaN,NaN,Rahul Madhav as | Priyamani as | Prathap Pot...,NaN,Anil Das,Baby Thotian
301610,1454118,Orozquista Revolution,1912,NaN,Pascual Orozco's revolutionary struggle in nor...,<NA>,NaN,NaN,NaN,https://a.ltrbxd.com/resized/film-poster/5/9/3...,NaN,NaN
72609,1086751,The Big Shakedown,1934,A New Type of Racket Exposed! In This Thrillin...,Former bootlegger Dutch Barnes pressures neigh...,61,3.20,Crime | Drama,Charles Farrell as Jimmy Morrell | Bette Davis...,https://a.ltrbxd.com/resized/film-poster/6/5/4...,John Francis Dillon,Samuel Bischoff

In [67]:
import os

os.makedirs("../dataset/processed", exist_ok=True)

In [68]:
final_movies.to_csv(
    "../dataset/processed/05_movies_master.csv",
    index=False
)

print("Movie Master Dataset Saved Successfully")
print(final_movies.shape)

Movie Master Dataset Saved Successfully
(577523, 12)

In [82]:
languages = pd.read_csv("../dataset/raw/languages.csv")

print(languages.shape)

languages.sample(10)

(1038762, 3)

             id             type    language
247243  1193297         Language  Portuguese
475590  1401119         Language      French
519439  1442122         Language      French
483980  1408975         Language     English
605423  1523435         Language      Korean
881929  1788672         Language     English
182311  1136972         Language     English
693575  1607980         Language     English
875872  1782898         Language     Russian
617454  1534865  Spoken language     English

In [79]:
languages.groupby("id").size().sort_values(ascending=False).head()

id
1285566    21
1038152    20
1236380    17
1181951    15
1790829    15
dtype: int64

In [80]:
languages_clean = (
    languages.groupby("id", sort=False)["language"]
    .agg(lambda x: " | ".join(pd.unique(x)))
    .reset_index(name="languages")
)

In [81]:
languages[languages["language"] == "Hindi"]

              id              type language
51       1000021   Spoken language    Hindi
271      1000115   Spoken language    Hindi
682      1000307   Spoken language    Hindi
794      1000357   Spoken language    Hindi
1046     1000477   Spoken language    Hindi
...          ...               ...      ...
1038052  1940910          Language    Hindi
1038162  1941021          Language    Hindi
1038491  1941328          Language    Hindi
1038561  1941398  Primary language    Hindi
1038563  1941398   Spoken language    Hindi

[10505 rows x 3 columns]

In [87]:
print(
    languages[languages["language"] == "Hindi"]["id"].nunique()
)

9538

In [89]:
hindi_ids = languages[
    languages["language"] == "Hindi"
]["id"].unique()

movies[movies["id"].isin(hindi_ids)][
    ["id", "name", "date"]
].head(50)

           id                                 name    date
20    1000021  Spider-Man: Across the Spider-Verse  2023.0
114   1000115                         The Avengers  2012.0
306   1000307                             Eternals  2021.0
356   1000357                    Chungking Express  1994.0
476   1000477                           Life of Pi  2012.0
492   1000493                           Monkey Man  2024.0
544   1000545               The Darjeeling Limited  2007.0
612   1000613                  Slumdog Millionaire  2008.0
997   1000998                                 Lion  2016.0
1055  1001056   Close Encounters of the Third Kind  1977.0
1280  1001281                                 2012  2009.0
1353  1001354                       The Half of It  2020.0
1435  1001436                           Extraction  2020.0
2301  1002302                             3 Idiots  2009.0
2466  1002467    Harold & Kumar Go to White Castle  2004.0
2596  1002597                    The Mask of Zorro  1998.0
2719  1002720                      Black Narcissus  1947.0
3340  1003341                               Gandhi  1982.0
3490  1003491                        Project Power  2020.0
3655  1003656                      The White Tiger  2021.0
3707  1003708                 Seven Years in Tibet  1997.0
3954  1003955                           The Bubble  2022.0
4302  1004303                         Hotel Mumbai  2018.0
4331  1004332                        Lust, Caution  2007.0
4402  1004403                  Like Stars on Earth  2007.0
4703  1004704                         The Lunchbox  2013.0
4916  1004917                 Dragonball Evolution  2009.0
4946  1004947         Mowgli: Legend of the Jungle  2018.0
5047  1005048                               Dangal  2016.0
5119  1005120                         Om Shanti Om  2007.0
5402  1005403                      It Lives Inside  2023.0
5457  1005458                                Jawan  2023.0
5528  1005529                            12th Fail  2023.0
5631  1005632                                   PK  2014.0
5662  1005663          Around the World in 80 Days  2004.0
5822  1005823                      Laapataa Ladies  2023.0
6109  1006110                            Andhadhun  2018.0
6189  1006190          Dilwale Dulhania Le Jayenge  1995.0
6203  1006204             Kabhi Khushi Kabhie Gham  2001.0
6232  1006233             The Hundred-Foot Journey  2014.0
6343  1006344                  Gangubai Kathiawadi  2022.0
6361  1006362                               Animal  2023.0
6378  1006379             Zindagi Na Milegi Dobara  2011.0
6382  1006383                       Station Eleven  2021.0
6500  1006501       The Best Exotic Marigold Hotel  2011.0
6522  1006523    Lagaan: Once Upon a Time in India  2001.0
6531  1006532                    All That Breathes  2022.0
6660  1006661                              Pathaan  2023.0
6683  1006684                              Tumbbad  2018.0
6750  1006751          Gangs of Wasseypur – Part 1  2012.0

In [90]:
final_movies = final_movies.merge(
    languages_clean,
    left_on="movie_id",
    right_on="id",
    how="left"
)

final_movies = final_movies.drop(columns=["id"])

In [91]:
final_movies.head()

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,genres,main_cast,poster_url,director,producer,languages
0,1000001,Barbie,2023,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114,3.86,Comedy | Adventure,Margot Robbie as Barbie | Ryan Gosling as Ken ...,https://a.ltrbxd.com/resized/film-poster/2/7/7...,Greta Gerwig,Tom Ackerley | Margot Robbie | Robbie Brenner,English
1,1000002,Parasite,2019,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133,4.56,Comedy | Thriller | Drama,Song Kang-ho as Kim Ki-taek | Lee Sun-kyun as ...,https://a.ltrbxd.com/resized/film-poster/4/2/6...,Bong Joon-ho,Jang Young-hwan | Kwak Sin-ae | Moon Yang-kwon,Korean | English | German
2,1000003,Everything Everywhere All at Once,2022,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140,4.30,Science Fiction | Adventure | Comedy | Action,Michelle Yeoh as Evelyn Wang | Ke Huy Quan as ...,https://a.ltrbxd.com/resized/film-poster/4/7/4...,Daniel Scheinert | Daniel Kwan,Joe Russo | Anthony Russo | Jonathan Wang,English | Cantonese | Chinese
3,1000004,Fight Club,1999,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139,4.27,Drama,Edward Norton as Narrator | Brad Pitt as Tyler...,https://a.ltrbxd.com/resized/film-poster/5/1/5...,David Fincher,Ross Grayson Bell | Ceán Chaffin | Art Linson,English
4,1000005,La La Land,2016,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129,4.09,Drama | Comedy | Music | Romance,Ryan Gosling as Sebastian | Emma Stone as Mia ...,https://a.ltrbxd.com/resized/film-poster/2/4/0...,Damien Chazelle,Jordan Horowitz | Fred Berger | Marc Platt,English

In [92]:
countries = pd.read_csv("../dataset/raw/countries.csv")

print(countries.shape)

countries.head()

(693476, 2)

        id      country
0  1000001           UK
1  1000001          USA
2  1000002  South Korea
3  1000003          USA
4  1000004      Germany

In [94]:
countries_clean = (
    countries.groupby("id", sort=False)["country"]
    .agg(lambda x: " | ".join(pd.unique(x)))
    .reset_index(name="countries")
)

countries_clean.head()

        id        countries
0  1000001         UK | USA
1  1000002      South Korea
2  1000003              USA
3  1000004    Germany | USA
4  1000005  Hong Kong | USA

In [95]:
final_movies = final_movies.merge(
    countries_clean,
    left_on="movie_id",
    right_on="id",
    how="left"
)

final_movies = final_movies.drop(columns=["id"])

print(final_movies.shape)
final_movies.head()

(577523, 14)

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,genres,main_cast,poster_url,director,producer,languages,countries
0,1000001,Barbie,2023,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114,3.86,Comedy | Adventure,Margot Robbie as Barbie | Ryan Gosling as Ken ...,https://a.ltrbxd.com/resized/film-poster/2/7/7...,Greta Gerwig,Tom Ackerley | Margot Robbie | Robbie Brenner,English,UK | USA
1,1000002,Parasite,2019,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133,4.56,Comedy | Thriller | Drama,Song Kang-ho as Kim Ki-taek | Lee Sun-kyun as ...,https://a.ltrbxd.com/resized/film-poster/4/2/6...,Bong Joon-ho,Jang Young-hwan | Kwak Sin-ae | Moon Yang-kwon,Korean | English | German,South Korea
2,1000003,Everything Everywhere All at Once,2022,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140,4.30,Science Fiction | Adventure | Comedy | Action,Michelle Yeoh as Evelyn Wang | Ke Huy Quan as ...,https://a.ltrbxd.com/resized/film-poster/4/7/4...,Daniel Scheinert | Daniel Kwan,Joe Russo | Anthony Russo | Jonathan Wang,English | Cantonese | Chinese,USA
3,1000004,Fight Club,1999,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139,4.27,Drama,Edward Norton as Narrator | Brad Pitt as Tyler...,https://a.ltrbxd.com/resized/film-poster/5/1/5...,David Fincher,Ross Grayson Bell | Ceán Chaffin | Art Linson,English,Germany | USA
4,1000005,La La Land,2016,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129,4.09,Drama | Comedy | Music | Romance,Ryan Gosling as Sebastian | Emma Stone as Mia ...,https://a.ltrbxd.com/resized/film-poster/2/4/0...,Damien Chazelle,Jordan Horowitz | Fred Berger | Marc Platt,English,Hong Kong | USA

In [96]:
final_movies.to_csv(
    "../dataset/processed/06_movies_with_languages_countries.csv",
    index=False
)

print("Checkpoint Saved")

Checkpoint Saved

In [97]:
countries = pd.read_csv("../dataset/raw/countries.csv")

print(countries.shape)
countries.head()

(693476, 2)

        id      country
0  1000001           UK
1  1000001          USA
2  1000002  South Korea
3  1000003          USA
4  1000004      Germany

In [98]:
countries_clean = (
    countries.groupby("id", sort=False)["country"]
    .agg(lambda x: " | ".join(pd.unique(x)))
    .reset_index(name="countries")
)

countries_clean.head()

        id        countries
0  1000001         UK | USA
1  1000002      South Korea
2  1000003              USA
3  1000004    Germany | USA
4  1000005  Hong Kong | USA

In [99]:
final_movies = final_movies.merge(
    countries_clean,
    left_on="movie_id",
    right_on="id",
    how="left"
)

final_movies = final_movies.drop(columns=["id"])

print(final_movies.shape)

(577523, 15)

In [100]:
studios = pd.read_csv("../dataset/raw/studios.csv")

print(studios.shape)
studios.head()

(679283, 2)

        id                   studio
0  1000001  LuckyChap Entertainment
1  1000001             Heyday Films
2  1000001           NB/GG Pictures
3  1000001                   Mattel
4  1000001    Warner Bros. Pictures

In [101]:
studios["rank"] = studios.groupby("id").cumcount()

studios = studios[studios["rank"] < 3]

In [104]:
studios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 626151 entries, 0 to 679280
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      626151 non-null  int64
 1   studio  626141 non-null  object
 2   rank    626151 non-null  int64
dtypes: int64(2), object(1)
memory usage: 19.1+ MB

In [105]:
studios[studios["studio"].isna()].head()

             id studio  rank
347347  1259717    NaN     0
411467  1350206    NaN     0
473794  1450762    NaN     0
534117  1565428    NaN     0
541076  1579904    NaN     0

In [106]:
studios_clean = (
    studios.groupby("id", sort=False)["studio"]
    .agg(lambda x: " | ".join(x.dropna().astype(str).unique()))
    .reset_index(name="studios")
)

studios_clean.head()

        id                                            studios
0  1000001  LuckyChap Entertainment | Heyday Films | NB/GG...
1  1000002                                       Barunson E&A
2  1000003          IAC Films | AGBO | Ley Line Entertainment
3  1000004  Fox 2000 Pictures | Regency Enterprises | The ...
4  1000005  Summit Entertainment | Black Label Media | Gil...

In [109]:
final_movies = final_movies.merge(
    studios_clean,
    left_on="movie_id",
    right_on="id",
    how="left"
)

final_movies = final_movies.drop(columns=["id"])

print(final_movies.shape)

(577523, 17)

In [110]:
final_movies.to_csv(
    "../dataset/processed/07_movies_with_country_studio.csv",
    index=False
)

print("Checkpoint Saved")
print(final_movies.shape)

Checkpoint Saved
(577523, 17)

In [111]:
themes = pd.read_csv("../dataset/raw/themes.csv")

print(themes.shape)

themes.head()

(125641, 2)

        id                                              theme
0  1000001                   Humanity and the world around us
1  1000001                             Crude humor and satire
2  1000001                        Moving relationship stories
3  1000001     Emotional and captivating fantasy storytelling
4  1000001  Surreal and thought-provoking visions of life ...

In [112]:
themes_clean = (
    themes.groupby("id", sort=False)["theme"]
    .agg(lambda x: " | ".join(x.dropna().astype(str).unique()[:10]))
    .reset_index(name="themes")
)

themes_clean.head()

        id                                             themes
0  1000001  Humanity and the world around us | Crude humor...
1  1000002  Humanity and the world around us | Intense vio...
2  1000003  Humanity and the world around us | Moving rela...
3  1000004  Intense violence and sexual transgression | Hu...
4  1000005  Song and dance | Humanity and the world around...

In [113]:
final_movies = final_movies.merge(
    themes_clean,
    left_on="movie_id",
    right_on="id",
    how="left"
)

final_movies = final_movies.drop(columns=["id"])

print(final_movies.shape)

(577523, 18)

In [116]:
releases = pd.read_csv("../dataset/raw/releases.csv")

print(releases.shape)

releases.sample(10)

(1332782, 5)

              id             country        date        type rating
53425    1001029             Denmark  2022-10-02  Theatrical    NaN
625368   1198179               Spain  2016-05-23  Theatrical    NaN
1308964  1899659             Ukraine  2023-09-16     Digital    NaN
307696   1024379  Russian Federation  2021-09-16     Digital    NaN
1298723  1881097              Greece  1929-11-25    Premiere    NaN
586925   1168478           Hong Kong  1970-12-10  Theatrical    NaN
128968   1003701         Netherlands  2019-04-17     Digital     AL
659944   1226512                 USA  2017-02-01     Digital    NaN
1054495  1600243              France  2019-04-17  Theatrical    NaN
1041542  1586634               Japan  2001-10-13  Theatrical    NaN

In [115]:
releases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1332782 entries, 0 to 1332781
Data columns (total 5 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   id       1332782 non-null  int64
 1   country  1332782 non-null  object
 2   date     1332782 non-null  object
 3   type     1332782 non-null  object
 4   rating   333980 non-null   object
dtypes: int64(1), object(4)
memory usage: 50.8+ MB

In [117]:
print(final_movies.shape)

(577523, 18)

In [118]:
final_movies.isnull().sum().sort_values(ascending=False)

themes             553190
avg_rating         501633
tagline            480406
producer           380895
studios_y          277271
studios_x          277271
runtime_minutes    181570
countries_x        180054
countries_y        180054
genres             142020
main_cast          140183
overview           132780
director           108184
poster_url          93642
release_year        56494
languages           10778
title                   8
movie_id                0
dtype: int64

In [119]:
print(final_movies.duplicated().sum())

0

In [120]:
print(final_movies["movie_id"].nunique())
print(len(final_movies))

577523
577523

In [121]:
final_movies.sample(10)

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,genres,main_cast,poster_url,director,producer,languages,countries_x,countries_y,studios_x,studios_y,themes
501864,1815099,Poetry Man,2010,NaN,"Short - Based on a true story, Jimmy, an aspir...",<NA>,NaN,NaN,NaN,https://a.ltrbxd.com/resized/film-poster/2/7/0...,NaN,NaN,English,NaN,NaN,NaN,NaN,NaN
48111,1054818,The Age of Success,1988,NaN,Kim Pan-chok (means “sales promotion”) is assi...,110,3.56,Drama | Comedy,Ahn Sung-ki as Kim Pan-chok | Lee Hye-young as...,https://a.ltrbxd.com/resized/film-poster/2/8/0...,Jang Sun-woo,NaN,Korean,South Korea,South Korea,HwangKiSung Films | Korean Academy of Film Arts,HwangKiSung Films | Korean Academy of Film Arts,NaN
1913,1001929,Demolition,2015,Life: Some disassembly required.,An emotionally desperate investment banker fin...,101,3.54,Comedy | Drama,Jake Gyllenhaal as Davis Mitchell | Naomi Watt...,https://a.ltrbxd.com/resized/sm/upload/eq/0m/h...,Jean-Marc Vallée,Sidney Kimmel | Trent Luckinbill | Molly Smith,English,USA,USA,Sidney Kimmel Entertainment | Mr. Mudd Product...,Sidney Kimmel Entertainment | Mr. Mudd Product...,Moving relationship stories | Humanity and the...
383999,1604432,A Wholly Healthy Glasgow,1988,NaN,"A fresh-faced gym instructor, Murdo Caldwell, ...",70,NaN,TV Movie | Comedy,Gerard Kelly as Charley Hood | Paul Higgins as...,https://a.ltrbxd.com/resized/film-poster/3/6/1...,Richard Wilson,Bill Bryden,English,NaN,NaN,NaN,NaN,NaN
439223,1704949,Come To Rest,1977,NaN,"Tired of the city life, the Botha family decid...",94,NaN,Comedy,NaN,https://a.ltrbxd.com/resized/film-poster/4/6/5...,NaN,NaN,Afrikaans,NaN,NaN,NaN,NaN,NaN
448449,1721711,관계 : 특별한 형수,2019,NaN,NaN,<NA>,NaN,Romance,Shin Yeon-woo as Joon-pyo | Seo Won-I as Eun-h...,https://a.ltrbxd.com/resized/film-poster/9/6/4...,Kim Hwan,NaN,Korean,South Korea,South Korea,(주)영화사가을,(주)영화사가을,NaN
188864,1259167,Joseph and the Amazing Technicolor Dreamcoat,<NA>,NaN,The modernized story of Joseph from the Bible'...,<NA>,NaN,Family | Music,NaN,https://a.ltrbxd.com/resized/film-poster/1/0/0...,Jon M. Chu,Scott Sanders | Mara Jacobs | Lance Johnson,English,USA,USA,The Really Useful Group | Amazon MGM Studios |...,The Really Useful Group | Amazon MGM Studios |...,NaN
170064,1228874,The Horror,2015,NaN,"After their parents' death, the Rademacher twi...",76,NaN,Thriller,Raymond Creamer as Malcolm Rademacher | Schell...,https://a.ltrbxd.com/resized/film-poster/2/6/7...,Jerry J. White III,Raymond Creamer | Jerry J. White III | Sarah C...,English,USA,USA,Moondog Media,Moondog Media,NaN
511892,1831932,By Common Consent,1975,NaN,In a foreign port two boys come to a fisherman...,86,NaN,NaN,Michelle Abrahams as | Bill Buffery as | Jon...,NaN,Ron daniels | John Robins,Kenith Trodd,English,USA,USA,BBC TV,BBC TV,NaN
157640,1209446,Fishy Stones,1990,NaN,"After a well-executed jewelry store heist, two...",69,NaN,Comedy | Crime,Innocent Gumede as | Kay Magubane as | Hecto...,https://a.ltrbxd.com/resized/film-poster/3/9/9...,Tonie van der Merwe,Pedie Dippenaar,Zulu,South Africa,South Africa,Eurika Films,Eurika Films,NaN

In [122]:
final_movies["countries"] = final_movies["countries_x"].combine_first(
    final_movies["countries_y"]
)

final_movies = final_movies.drop(
    columns=["countries_x", "countries_y"]
)

In [123]:
final_movies["studios"] = final_movies["studios_x"].combine_first(
    final_movies["studios_y"]
)

final_movies = final_movies.drop(
    columns=["studios_x", "studios_y"]
)

In [124]:
final_movies.sample(10)

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,genres,main_cast,poster_url,director,producer,languages,themes,countries,studios
254710,1371180,Sealed Video 45: Bakkuyoraku,2020,NaN,45th entry in the 'Sealed Video' franchise fro...,60,NaN,Horror,Ryujin Onizuka as | Misaki Akutsu as Sealed v...,https://a.ltrbxd.com/resized/film-poster/9/9/2...,Ryujin Onizuka,NaN,Japanese,NaN,Japan,At Entertainment Inc.
507108,1823794,Timon von Athen,1976,NaN,NaN,<NA>,NaN,Drama,Wolfgang Reichmann as Timon | Günter Strack as...,NaN,Oswald Döpke,NaN,German,NaN,Germany,NaN
149164,1196339,A Connecticut Yankee in King Arthur's Court,1970,NaN,Animated Remake,74,NaN,Animation,Orson Bean as Hank / Sir Boss (voice) | Barbar...,https://a.ltrbxd.com/resized/film-poster/3/7/2...,Zoran Janjic,NaN,English,NaN,NaN,Air Programs International (API)
506198,1822444,Spasibo,2003,NaN,"Однажды одинокий дьявол, безумно любящий свою ...",88,NaN,Fantasy | Comedy,Andrei Tashkov as | Irina Kupchenko as | Ser...,https://a.ltrbxd.com/resized/film-poster/5/6/1...,Dmytro Tomashpolskyi,NaN,English,NaN,NaN,NaN
261476,1383015,Mount Hakone,1962,NaN,Japanese drama.,105,NaN,Drama,Yūzō Kayama as | Yuriko Hoshi as | Chieko Hi...,https://a.ltrbxd.com/resized/film-poster/2/6/3...,Yūzō Kawashima,NaN,Japanese,NaN,Japan,TOHO
230091,1328533,Love in the Time of Revolution,2022,NaN,Echoing with voices from the streets of Hong K...,107,NaN,NaN,NaN,https://a.ltrbxd.com/resized/film-poster/9/3/8...,Ngan Twinkle Chi-Sing,NaN,Cantonese,NaN,Hong Kong,NaN
97552,1120928,FLCL Shoegaze,2023,NaN,Taking place 10 years after the events of FLCL...,69,NaN,NaN,NaN,https://a.ltrbxd.com/resized/sm/upload/97/jg/d...,NaN,NaN,English,NaN,NaN,NaN
211394,1296809,Der Teufel mit den drei goldenen Haaren,2009,NaN,German TV adaptation of Grimm‘s fairy tale “Th...,74,NaN,Fantasy | TV Movie | Mystery,Béla Baptiste as Hans | Ina-Alice Kopp as Prin...,https://a.ltrbxd.com/resized/film-poster/7/3/2...,Hans-Günther Bücking,NaN,German,NaN,Germany,Provobis Film | ZDF
413406,1658179,"Хіппініада, або Материк кохання",1997,NaN,NaN,88,NaN,NaN,Svitlana Avtukhova as | Boryslav Brondukov as...,https://a.ltrbxd.com/resized/film-poster/9/3/5...,Andrei Benkendorf,NaN,Ukrainian,NaN,Ukraine,Dovzhenko Film Studios
536734,1872130,Les Schtroumpfs - Le Genie De La Lampe -,<NA>,NaN,NaN,<NA>,NaN,Animation,NaN,https://a.ltrbxd.com/resized/film-poster/6/1/2...,NaN,NaN,French,NaN,NaN,NaN

In [125]:
final_movies.to_csv(
    "../dataset/processed/movieverse_master_dataset.csv",
    index=False
)