In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("../dataset/processed/movieverse_master_dataset.csv")

print("Shape:", movies.shape)

movies.head()

C:\Users\HARIOM SUTHAR\AppData\Local\Temp\ipykernel_5896\904772456.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv("../dataset/processed/movieverse_master_dataset.csv")

Shape: (577523, 16)

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,genres,main_cast,poster_url,director,producer,languages,themes,countries,studios
0,1000001,Barbie,2023.0,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114.0,3.86,Comedy | Adventure,Margot Robbie as Barbie | Ryan Gosling as Ken ...,https://a.ltrbxd.com/resized/film-poster/2/7/7...,Greta Gerwig,Tom Ackerley | Margot Robbie | Robbie Brenner,English,Humanity and the world around us | Crude humor...,UK | USA,LuckyChap Entertainment | Heyday Films | NB/GG...
1,1000002,Parasite,2019.0,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133.0,4.56,Comedy | Thriller | Drama,Song Kang-ho as Kim Ki-taek | Lee Sun-kyun as ...,https://a.ltrbxd.com/resized/film-poster/4/2/6...,Bong Joon-ho,Jang Young-hwan | Kwak Sin-ae | Moon Yang-kwon,Korean | English | German,Humanity and the world around us | Intense vio...,South Korea,Barunson E&A
2,1000003,Everything Everywhere All at Once,2022.0,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140.0,4.30,Science Fiction | Adventure | Comedy | Action,Michelle Yeoh as Evelyn Wang | Ke Huy Quan as ...,https://a.ltrbxd.com/resized/film-poster/4/7/4...,Daniel Scheinert | Daniel Kwan,Joe Russo | Anthony Russo | Jonathan Wang,English | Cantonese | Chinese,Humanity and the world around us | Moving rela...,USA,IAC Films | AGBO | Ley Line Entertainment
3,1000004,Fight Club,1999.0,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139.0,4.27,Drama,Edward Norton as Narrator | Brad Pitt as Tyler...,https://a.ltrbxd.com/resized/film-poster/5/1/5...,David Fincher,Ross Grayson Bell | Ceán Chaffin | Art Linson,English,Intense violence and sexual transgression | Hu...,Germany | USA,Fox 2000 Pictures | Regency Enterprises | The ...
4,1000005,La La Land,2016.0,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129.0,4.09,Drama | Comedy | Music | Romance,Ryan Gosling as Sebastian | Emma Stone as Mia ...,https://a.ltrbxd.com/resized/film-poster/2/4/0...,Damien Chazelle,Jordan Horowitz | Fred Berger | Marc Platt,English,Song and dance | Humanity and the world around...,Hong Kong | USA,Summit Entertainment | Black Label Media | Gil...

In [3]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 577523 entries, 0 to 577522
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   movie_id         577523 non-null  int64
 1   title            577515 non-null  object
 2   release_year     521029 non-null  float64
 3   tagline          97117 non-null   object
 4   overview         444743 non-null  object
 5   runtime_minutes  395953 non-null  float64
 6   avg_rating       75890 non-null   float64
 7   genres           435503 non-null  object
 8   main_cast        437340 non-null  object
 9   poster_url       483881 non-null  object
 10  director         469339 non-null  object
 11  producer         196628 non-null  object
 12  languages        566745 non-null  object
 13  themes           24333 non-null   object
 14  countries        397469 non-null  object
 15  studios          300252 non-null  object
dtypes: float64(3), int64(1), object(12)
memory usage: 70.5+ MB

In [5]:
movies.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
movie_id,577523.0,NaN,NaN,NaN,1444159.332158,281924.938619,1000001.0,1189092.0,1431349.0,1693954.0,1941597.0
title,577515,509363,Home,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN
release_year,521029.0,NaN,NaN,NaN,1997.222471,26.26842,1890.0,1983.0,2007.0,2017.0,2031.0
tagline,97117,95097,Cert 18,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
overview,444743,435042,Mexican feature film,835,NaN,NaN,NaN,NaN,NaN,NaN,NaN
runtime_minutes,395953.0,NaN,NaN,NaN,108.25721,204.929849,60.0,81.0,91.0,105.0,72000.0
avg_rating,75890.0,NaN,NaN,NaN,3.21609,0.431998,0.88,2.97,3.27,3.5,4.69
genres,435503,12948,Drama,73393,NaN,NaN,NaN,NaN,NaN,NaN,NaN
main_cast,437340,425579,Ramana Maharshi as Self (archive footage) | Sr...,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
poster_url,483881,483133,https://a.ltrbxd.com/resized/film-poster/4/8/1...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
director,469339,187140,Gilbert M. Anderson,283,NaN,NaN,NaN,NaN,NaN,NaN,NaN
producer,196628,139247,Auguste Lumière | Louis Lumière,361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
languages,566745,7220,English,208499,NaN,NaN,NaN,NaN,NaN,NaN,NaN
themes,24333,17930,Song and dance | Bollywood emotional dramas,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN
countries,397469,9360,USA,86032,NaN,NaN,NaN,NaN,NaN,NaN,NaN
studios,300252,158482,Toei Company,1629,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
print("Duplicate Rows :", movies.duplicated().sum())

Duplicate Rows : 0

In [8]:
print("Duplicate Movie IDs :", movies["movie_id"].duplicated().sum())

Duplicate Movie IDs : 0

In [9]:
print("Duplicate Titles :", movies["title"].duplicated().sum())

Duplicate Titles : 68159

### missing values

In [10]:
missing = (
    movies.isnull()
    .sum()
    .sort_values(ascending=False)
)

missing

themes             553190
avg_rating         501633
tagline            480406
producer           380895
studios            277271
runtime_minutes    181570
countries          180054
genres             142020
main_cast          140183
overview           132780
director           108184
poster_url          93642
release_year        56494
languages           10778
title                   8
movie_id                0
dtype: int64

In [10]:
missing_percentage = (
    movies.isnull().mean() * 100
).round(2)

missing_percentage.sort_values(ascending=False)

themes             95.79
avg_rating         86.86
tagline            83.18
producer           65.95
studios            48.01
runtime_minutes    31.44
countries          31.18
genres             24.59
main_cast          24.27
overview           22.99
director           18.73
poster_url         16.21
release_year        9.78
languages           1.87
title               0.00
movie_id            0.00
dtype: float64

### title clean

In [11]:
movies["title"] = (
    movies["title"]
    .astype(str)
    .str.strip()
)

### overview

In [12]:
movies["overview"] = movies["overview"].fillna(
    "Overview not available."
)

### tagline

In [13]:
movies["tagline"] = movies["tagline"].fillna("")

### cast

In [14]:
movies["main_cast"] = movies["main_cast"].fillna(
    "Cast information unavailable"
)

### countries

In [15]:
movies["countries"] = movies["countries"].fillna(
    "Unknown"
)

### producer

In [16]:
movies["producer"] = movies["producer"].fillna(
    "Unknown"
)

### studio

In [17]:
movies["studios"] = movies["studios"].fillna(
    "Unknown"
)

### language

In [18]:
movies["languages"] = movies["languages"].fillna(
    "Unknown"
)

### datatype of data and time

In [19]:
movies["release_year"] = movies["release_year"].astype("Int64")

movies["runtime_minutes"] = movies["runtime_minutes"].astype("Int64")

In [20]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 577523 entries, 0 to 577522
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   movie_id         577523 non-null  int64
 1   title            577523 non-null  object
 2   release_year     521029 non-null  Int64
 3   tagline          577523 non-null  object
 4   overview         577523 non-null  object
 5   runtime_minutes  395953 non-null  Int64
 6   avg_rating       75890 non-null   float64
 7   genres           435503 non-null  object
 8   main_cast        577523 non-null  object
 9   poster_url       483881 non-null  object
 10  director         469339 non-null  object
 11  producer         577523 non-null  object
 12  languages        577523 non-null  object
 13  themes           24333 non-null   object
 14  countries        577523 non-null  object
 15  studios          577523 non-null  object
dtypes: Int64(2), float64(1), int64(1), object(12)
memory usage: 71.6+ MB

In [21]:
movies.isnull().sum()

movie_id                0
title                   0
release_year        56494
tagline                 0
overview                0
runtime_minutes    181570
avg_rating         501633
genres             142020
main_cast               0
poster_url          93642
director           108184
producer                0
languages               0
themes             553190
countries               0
studios                 0
dtype: int64

### check empty string

In [22]:
for col in movies.select_dtypes(include="object").columns:
    empty = (movies[col].str.strip() == "").sum()
    print(f"{col}: {empty}")

title: 0
tagline: 480406
overview: 1
genres: 0
main_cast: 0
poster_url: 0
director: 0
producer: 0
languages: 0
themes: 0
countries: 0
studios: 0

### release year validation

In [23]:
print("Minimum Year:", movies["release_year"].min())
print("Maximum Year:", movies["release_year"].max())

Minimum Year: 1890
Maximum Year: 2031

In [24]:
movies["runtime_minutes"].describe()

count      395953.0
mean      108.25721
std      204.929849
min            60.0
25%            81.0
50%            91.0
75%           105.0
max         72000.0
Name: runtime_minutes, dtype: Float64

### rating validation

In [25]:
movies["avg_rating"].describe()

count    75890.000000
mean         3.216090
std          0.431998
min          0.880000
25%          2.970000
50%          3.270000
75%          3.500000
max          4.690000
Name: avg_rating, dtype: float64

In [26]:
movies[
    (movies["avg_rating"] < 0) |
    (movies["avg_rating"] > 5)
]

Empty DataFrame
Columns: [movie_id, title, release_year, tagline, overview, runtime_minutes, avg_rating, genres, main_cast, poster_url, director, producer, languages, themes, countries, studios]
Index: []

### poster URL validation

In [27]:
movies["poster_url"].str.startswith("http").value_counts(dropna=False)

poster_url
True    483881
NaN      93642
Name: count, dtype: int64

### Duplicate titles by year

In [28]:
movies.groupby(
    ["title", "release_year"]
).size().sort_values(ascending=False).head(20)

title                             release_year
untitled                          1995            10
Alone                             2020             8
untitled                          1996             8
Fog                               2023             6
Dolly - Il sesso biondo           1979             6
Ryōjoku: Komasu                   1979             6
Split                             2016             6
untitled                          1993             6
                                  1994             6
Ganbare! Bokura no Hit and Run    1979             5
A Dama de Branco                  1978             5
7 oder Wie halte ich die Zeit an  2023             5
Mother-Hen                        1937             5
Unknown                           2023             5
Unfinished Business from Beyond   2023             5
Victoria                          2020             5
Vote (Chala Viluvainadi)          2023             5
Hero                              2022             4
La justicia de Pancho Villa       1939             4
Eine Frau kommt in die Tropen     1938             4
dtype: int64

In [32]:
print("Final Shape:", movies.shape)

movies.head()

Final Shape: (577523, 16)

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,genres,main_cast,poster_url,director,producer,languages,themes,countries,studios
0,1000001,Barbie,2023,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114,3.86,Comedy | Adventure,Margot Robbie as Barbie | Ryan Gosling as Ken ...,https://a.ltrbxd.com/resized/film-poster/2/7/7...,Greta Gerwig,Tom Ackerley | Margot Robbie | Robbie Brenner,English,Humanity and the world around us | Crude humor...,UK | USA,LuckyChap Entertainment | Heyday Films | NB/GG...
1,1000002,Parasite,2019,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133,4.56,Comedy | Thriller | Drama,Song Kang-ho as Kim Ki-taek | Lee Sun-kyun as ...,https://a.ltrbxd.com/resized/film-poster/4/2/6...,Bong Joon-ho,Jang Young-hwan | Kwak Sin-ae | Moon Yang-kwon,Korean | English | German,Humanity and the world around us | Intense vio...,South Korea,Barunson E&A
2,1000003,Everything Everywhere All at Once,2022,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140,4.30,Science Fiction | Adventure | Comedy | Action,Michelle Yeoh as Evelyn Wang | Ke Huy Quan as ...,https://a.ltrbxd.com/resized/film-poster/4/7/4...,Daniel Scheinert | Daniel Kwan,Joe Russo | Anthony Russo | Jonathan Wang,English | Cantonese | Chinese,Humanity and the world around us | Moving rela...,USA,IAC Films | AGBO | Ley Line Entertainment
3,1000004,Fight Club,1999,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139,4.27,Drama,Edward Norton as Narrator | Brad Pitt as Tyler...,https://a.ltrbxd.com/resized/film-poster/5/1/5...,David Fincher,Ross Grayson Bell | Ceán Chaffin | Art Linson,English,Intense violence and sexual transgression | Hu...,Germany | USA,Fox 2000 Pictures | Regency Enterprises | The ...
4,1000005,La La Land,2016,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129,4.09,Drama | Comedy | Music | Romance,Ryan Gosling as Sebastian | Emma Stone as Mia ...,https://a.ltrbxd.com/resized/film-poster/2/4/0...,Damien Chazelle,Jordan Horowitz | Fred Berger | Marc Platt,English,Song and dance | Humanity and the world around...,Hong Kong | USA,Summit Entertainment | Black Label Media | Gil...

In [29]:
movies[
    (movies["title"] == "untitled") &
    (movies["release_year"] == 1995)
][["movie_id", "title", "release_year"]]

        movie_id     title  release_year
211819   1297545  untitled          1995
211820   1297546  untitled          1995
212433   1298616  untitled          1995
212434   1298617  untitled          1995
212435   1298618  untitled          1995
212436   1298619  untitled          1995
213066   1299688  untitled          1995
214304   1301787  untitled          1995
214305   1301788  untitled          1995
214956   1302902  untitled          1995

In [30]:
movies[movies["title"].str.strip() == ""]

Empty DataFrame
Columns: [movie_id, title, release_year, tagline, overview, runtime_minutes, avg_rating, genres, main_cast, poster_url, director, producer, languages, themes, countries, studios]
Index: []

In [31]:
(movies["title"].str.strip() == "").sum()

np.int64(0)

In [32]:
movies[
    (movies["title"] == "Split") &
    (movies["release_year"] == 2016)
][["movie_id", "title", "release_year"]]

        movie_id  title  release_year
202      1000203  Split          2016
68403    1081029  Split          2016
74097    1088736  Split          2016
121284   1154842  Split          2016
149976   1197607  Split          2016
189052   1259487  Split          2016

In [33]:
movies = movies[
    (movies["runtime_minutes"].isna()) |
    (
        (movies["runtime_minutes"] >= 60) &
        (movies["runtime_minutes"] <= 300)
    )
]

### save clean dataset

In [36]:
movies.to_csv(
    "../dataset/processed/movieverse_master_dataset_clean.csv",
    index=False
)

print("Clean Dataset Saved Successfully!")

Clean Dataset Saved Successfully!